# Generated by Django 5.1.4 on 2025-01-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Dummy Data',
                'verbose_name_plural': 'Dummy Data',
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
