# Generated by Django 5.1.4 on 2025-01-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dummydata',
            unique_together=set(),
        ),
    ]
